---
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS INSTANCES
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************

cp4waiops:


- project: cp4waiops-evtmgr
  instances:
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Event Manager
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-eventmanager
    kind: EventManager
    install: true
    # Version of the catalog subscription
    subscription_channel: v1.10
    starting_csv: noi.v1.6.0
    noi_version: 1.6.6
  # --------------------------------------------------------------------------------------------------------------------------------------
  # CP4WAIOPS Event Manager Demo Content
  # --------------------------------------------------------------------------------------------------------------------------------------
  - name: cp4waiops-eventmanager
    kind: EventManagerDemoContent
    install: true



# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS GLOBAL CONFIGURATION
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Storage Classes
# --------------------------------------------------------------------------------------------------------------------------------------

# Override the Storage Class auto detection (not_configured, ibmc-file-gold-gid, rook-cephfs, nfs-client, ...)
storage_class_file: $WAIOPS_STORAGE_CLASS_FILE        # LOCAL
storage_class_block: $WAIOPS_STORAGE_CLASS_BLOCK      # LOCAL


# --------------------------------------------------------------------------------------------------------------------------------------
# CP4WAIOPS Pull Registires
# --------------------------------------------------------------------------------------------------------------------------------------
entitled_registry: cp.icr.io
entitled_registry_user: cp
catalog_image: icr.io/cpopen/ibm-operator-catalog:latest


#Version of your OCP Cluster (override by setting manually - 4.6, 4.7,...)
ocp_major_version: automatic
