
# *************************************************************************************************************************************************
# --------------------------------------------------------------------------------------------------------------------------------------
# Patches
# --------------------------------------------------------------------------------------------------------------------------------------
# *************************************************************************************************************************************************


- name: 🩹 PATCH - Restart Demo UI
  shell: |
    oc delete pod $(oc get po -n cp4waiops-demo-ui |grep cp4waiops-demo-ui|awk '{print$1}') -n cp4waiops-demo-ui --ignore-not-found
  ignore_errors: yes


